const express = require('express');
const router = express.Router();
const { verifyToken } = require('../utils/jwt');
const {fileAddValidator,fileUpdateValidator} = require('../validators/fileValidator');
const fileController = require('../controller/file');
router.get('/list', verifyToken(), fileController.getList);
router.post('/add', verifyToken(), fileAddValidator, fileController.addFile);
router.put('/edit', verifyToken(), fileUpdateValidator, fileController.updateFile);
router.delete('/del/:id', verifyToken(), fileController.deleteFile);
module.exports = router;