# server.conf
[ req ]
default_bits = 2048
prompt = no
default_md = sha256
distinguished_name = dn
req_extensions = v3_req

[ dn ]
CN=myserver.local # 将 myserver.local 替换为你的服务器实际域名或 IP

[ v3_req ]
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
subjectAltName = @alt_names

[ alt_names ] # 定义多个别名
DNS.1 = myserver.local # 你的域名
DNS.2 = localhost        # 本地访问
IP.1 = 127.0.0.1         # 本地 IP